### ISSUE TITLE
Adding data to continue training failed.

### ISSUE THREAD

**Issue by SefaZeng** [EleutherAI/gpt-neox#860]
**Is your feature request related to a problem? Please describe.**
I trained a language model in about 4 datasets. And then I add some new datasets for translation. The config file is changing from:
```
    "train-data-paths": [
        "/data/pile-00-04-train_text_document",
        "/data/clue_pretrain_0-train_text_document",
    ],
    "train-data-weights": [40.0, 60.0],
```
to
```
    "train-data-paths": [
        "/data/pile-00-04-train_text_document",
        "/data/clue_pretrain_0-train_text_document",
        "/data/mt/en-zh-train_text_document",
        "/data/mt/ja-zh-train_text_document"
    ],
    "train-data-weights": [40.0, 40.0, 10.0, 10.0],
```
Then the training is failed with error message:
```
Traceback (most recent call last):
  File "/data/yard/workspace/gpt-neox/train.py", line 27, in <module>
    pretrain(neox_args=neox_args)
  File "/data/yard/workspace/gpt-neox/megatron/training.py", line 120, in pretrain
    iteration = train(
  File "/data/yard/workspace/gpt-neox/megatron/training.py", line 583, in train
    loss_dict, skipped_iter = train_step(
  File "/data/yard/workspace/gpt-neox/megatron/training.py", line 490, in train_step
    reduced_loss = train_step_pipe(
  File "/data/yard/workspace/gpt-neox/megatron/training.py", line 539, in train_step_pipe
    loss = model.train_batch(data_iter=data_iterator)
  File "/data/yard/workspace/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 305, in train_batch
    self._exec_schedule(sched)
  File "/data/yard/workspace/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 1312, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/data/yard/workspace/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 791, in _exec_load_micro_batch
    batch = self._next_batch()
  File "/data/yard/workspace/lib/python3.9/site-packages/deepspeed/runtime/pipe/engine.py", line 650, in _next_batch
    batch = next(self.data_iterator)
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 141, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1369] at entry 0 and [2049] at entry 1
```
Are there any arguments I missed for fine-tuning from a model? Or is there anything to fix this?
Any response is appreciated!

**Comment by Quentin-Anthony** [comment]
It's possible your dataset builder is overflowing when calculating the sample indices once you introduce more data, which is a bug we fixed in https://github.com/EleutherAI/gpt-neox/pull/835.

Can you try again with the latest commit?

**Comment by SefaZeng** [comment]
> It's possible your dataset builder is overflowing when calculating the sample indices once you introduce more data, which is a bug we fixed in #835.
> 
> Can you try again with the latest commit?

Thank you @Quentin-Anthony for your reply. I try to update the code with #835 , but it still failed.

**Comment by SefaZeng** [comment]
> > It's possible your dataset builder is overflowing when calculating the sample indices once you introduce more data, which is a bug we fixed in #835.
> > Can you try again with the latest commit?
> 
> Thank you @Quentin-Anthony for your reply. I try to update the code with #835 , but it still failed. And there are some error messages missed before:
> 
> ```
> Original Traceback (most recent call last):
>   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
>     return self.collate_fn(data)
>   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
>     return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
>   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
>     return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
>   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
>     return default_collate([torch.as_tensor(b) for b in batch])
>   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 140, in default_collate
>     out = elem.new(storage).resize_(len(batch), *list(elem.size()))
> RuntimeError: Trying to resize storage that is not resizable
> ```

Is it possible that the data size is too large, causing an OOM error?

**Comment by SefaZeng** [comment]
> > > It's possible your dataset builder is overflowing when calculating the sample indices once you introduce more data, which is a bug we fixed in #835.
> > > Can you try again with the latest commit?
> > 
> > 
> > Thank you @Quentin-Anthony for your reply. I try to update the code with #835 , but it still failed. And there are some error messages missed before:
> > ```
> > Original Traceback (most recent call last):
> >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
> >     data = fetcher.fetch(index)
> >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
> >     return self.collate_fn(data)
> >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
> >     return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
> >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
> >     return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
> >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
> >     return default_collate([torch.as_tensor(b) for b in batch])
> >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 140, in default_collate
> >     out = elem.new(storage).resize_(len(batch), *list(elem.size()))
> > RuntimeError: Trying to resize storage that is not resizable
> > ```
> 
> Is it possible that the data size is too large, causing an OOM error? Can gpt-neox load parts of the data?

I find my own machine translation data will cause this error. Are there any scripts to process the txt file to the required format for gpt-neox? I already changed the data to json file, but it seems something wrong with the preprocess.

**Comment by SefaZeng** [comment]
> > > > It's possible your dataset builder is overflowing when calculating the sample indices once you introduce more data, which is a bug we fixed in #835.
> > > > Can you try again with the latest commit?
> > > 
> > > 
> > > Thank you @Quentin-Anthony for your reply. I try to update the code with #835 , but it still failed. And there are some error messages missed before:
> > > ```
> > > Original Traceback (most recent call last):
> > >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
> > >     data = fetcher.fetch(index)
> > >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
> > >     return self.collate_fn(data)
> > >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
> > >     return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
> > >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
> > >     return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
> > >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
> > >     return default_collate([torch.as_tensor(b) for b in batch])
> > >   File "/data/yard/workspace/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 140, in default_collate
> > >     out = elem.new(storage).resize_(len(batch), *list(elem.size()))
> > > RuntimeError: Trying to resize storage that is not resizable
> > > ```
> > 
> > 
> > Is it possible that the data size is too large, causing an OOM error? Can gpt-neox load parts of the data?
> 
> I find my own machine translation data will cause this error. Are there any scripts to process the txt file to the required format for gpt-neox? I already changed the data to json file, but it seems something wrong with the preprocess.

I found `"train_micro_batch_size_per_gpu": 4,` is ok for pile, but it will cause this error. Change `"train_micro_batch_size_per_gpu"` to 1 is ok for my mt data. I don't know why.

**Comment by StellaAthena** [comment]
> I find my own machine translation data will cause this error. Are there any scripts to process the txt file to the required format for gpt-neox? I already changed the data to json file, but it seems something wrong with the preprocess.

While this is not the only format the library supports, I typically have data stored in jsonl files with the following structure:
```
{"text": "this is document number one."}
{"text": "this is document number two."}
{"text": "this is document number three."}
```

**Comment by SefaZeng** [comment]
> > I find my own machine translation data will cause this error. Are there any scripts to process the txt file to the required format for gpt-neox? I already changed the data to json file, but it seems something wrong with the preprocess.
> 
> While this is not the only format the library supports, I typically have data stored in jsonl files with the following structure:
> 
> ```
> {"text": "this is document number one."}
> {"text": "this is document number two."}
> {"text": "this is document number three."}
> ```

Thank you for your reply! I did change my data to the jsonl format like you showed here. I found if I change the `train_micro_batch_size_per_gpu` to 1, it went well. I am not sure the reason.

**Comment by StellaAthena** [comment]
@SefaZeng Can you post a link to download a small sample from your data and a command we can run to reproduce this effect?

To be clear, my understanding is that the current situation is:
1. Finetuning with Pile has no issue
2. Finetuning with your dataset causes `RuntimeError: Trying to resize storage that is not resizable` when MBS/GPU = 4
3. This error goes away when you set MBS/GPU = 1
4. Using the recommended jsonl format doesn’t make this error go away

Is that a correct summary?

**Comment by StellaAthena** [comment]
@SefaZeng following up

**Comment by Quentin-Anthony** [comment]
Closing due to inactivity. Feel free to re-open if you'd like to continue debugging @SefaZeng.

**Comment by cateto** [comment]
Is too many train steps cause same problem?
I try to 6400000 steps / batch size 16.
cause this error below.

```
RuntimeError: Trying to resize storage that is not resizable
```
